# Generated by Django 4.1.1 on 2022-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='register_time',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='register_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
