# Generated by Django 4.1.1 on 2022-10-05 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0003_userdetail_updated_at_alter_userdetail_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='register_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 23, 23, 41, 878827)),
        ),
    ]
