# Generated by Django 4.1.1 on 2022-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0004_alter_userdetail_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='register_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
