# Generated by Django 4.1.1 on 2022-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0005_alter_userdetail_register_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
